export type NavItems = {
  [key: string]: NavItem;
};

export type NavItem = {
  path: string;
  title: string;
};

// Generated by https://quicktype.io

export interface Page {
  id: number;
  title: string;
  slug: string;
  title_tag: string;
  meta_tag: string;
  content: string;
  is_active: number;
  template: string;
  created_by: number;
  updated_by: number;
  release_at: null;
  created_at: string;
  updated_at: string;
}
